### ISSUE TITLE
duplication of (chat?) packets

### ISSUE THREAD

**Issue by ghost** [PrismarineJS/numerous-alpaca#1]
when using serv.writeAll (i believe we've seen this before)

**Comment by mhsjlw** [comment]
https://github.com/PocketMine/PocketMine-MP/issues/1515

**Comment by rom1504** [comment]
this is probably https://github.com/mhsjlw/node-raknet/issues/9

**Comment by ghost** [comment]
it's also possible that we resend them because we never remove the player from the array. i've connected 2 times and it looks like i get sent the message 2 times. this is most likely the problem. we will need to figure out how to find out when the player disconnects first so that we can remove him/her from the array

**Comment by ghost** [comment]
#6

**Comment by ghost** [comment]
no longer occurs after removing the player from the list of players

**Comment by rom1504** [comment]
cool
